# -*- MakeFile -*-

#Variables
CC = gcc

f1=strings
f2=arrays
f3=pointers
f4=stdLibs
f5=switch
f6=scope
f7=variablesAndSpecifers
f8=varModifier
f9=recursion
f10=structs
f11=test

all: 
	$(CC) $(f1).c -o $(f1)
	$(CC) $(f2).c -o $(f2)
	$(CC) $(f3).c -o $(f3)
	$(CC) $(f4).c -o $(f4)
	$(CC) $(f5).c -o $(f5)
	$(CC) $(f6).c -o $(f6)
	$(CC) $(f7).c -o $(f7)
	$(CC) $(f8).c -o $(f8)
	$(CC) $(f9).c -o $(f9)
	$(CC) $(f10).c -o $(f10)
	$(CC) $(f11).c -o $(f11)

clean:
	rm $(f1) $(f2) $(f3) $(f4) $(f5) $(f6) $(f7) $(f8) $(f9) $(f10) $(11)