import java.util.*;

/**
 * @author 20hossainz
 *December 10, 2018
 *Calculate the total income amount, generated from three different types of ticket sales in a soccer match */
public class Tickets {

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// Define variables
		Scanner input = new Scanner(System.in);
		int a;
		int b;
		int c;
		double t;
		
		// Read in integers
		System.out.println("Enter the number of ticket type a");
		a = input.nextInt();
		System.out.println("Enter the number of ticket type b");
		b = input.nextInt();
		System.out.println("Enter the  number of ticket type c");
		c = input.nextInt();
		
		
		// Calculate the total amount of income generated by the ticket sales
		t = (a*15)+(b*12)+(c*9);
		System.out.println("The total amount generated by the ticket sales is " + "$ " + t);
		
		//print the answer
		
		
		
		

	}

}
